version: '2'
services:
  web:
    container_name: nginx
    image: nginx
    ports:
    - "8080:80"
    links:
    - app
    volumes:
    - "./:/var/www"
    - "./vhost.conf:/etc/nginx/conf.d/030-laravel.conf:ro"

  app:
    container_name: php
    image: recchia/php-fpm:7.2
    links:
      - database
    volumes:
      - "./:/var/www"
    working_dir: "/var/www"
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Database
  database:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

volumes:
  dbdata: